### PR TITLE
Update for Vapor 4

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This depends on https://github.com/alexsteinerde/graphql-kit/pull/4.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@alexsteinerde ready for review 🙂

**Comment by alexsteinerde** [comment]
Thanks for the PR.
I just tagged GraphiQL-Vapor and GraphQLKit with 2.0.0. 
Could you please use the tag instead of the branch?

**Comment by MaxDesiatov** [comment]
Thank you very much! I've updated the manifest to use tags.

**Comment by alexsteinerde** [comment]
Great, thanks for updating the manifest. It seems fine for me so far.
Thanks for your great support upgrading the whole GraphQL package for Vapor 4!

**Comment by MaxDesiatov** [comment]
No problem, happy to help! 🙂

**Pull request merged**
